### ISSUE TITLE
Docker Container auf VM bringen

### ISSUE THREAD

**Issue by thgnaedi** [thgnaedi/DeepRain#21]
Tensorflow Container mit GPU unterstützung auf VM bringen

https://tensorchiefs.github.io/dl_course_2018/docker.html

**Comment by PaddyK92** [comment]
https://www.tensorflow.org/install/docker

**Comment by timethethyme** [comment]
**Tensorflow 1.5:**
docker run -it tensorflow/tensorflow:1.5.0 bash / python  / import tensorflow 
[Tensorflow Test:](https://www.oreilly.com/library/view/deep-learning-with/9781786469786/3bdee8f3-ca88-438a-8141-42d2a12db71d.xhtml)

**TensorChiefs:** 
_CPU Support: _
docker run -p 7777:8888 -p 6006:6006 -it oduerr/tf_docker:cpu_r
_GPU Support:_
docker run -p 7777:8888 -p 6006:6006 -it oduerr/tf_docker:gpu_r_tfp

_To access a directory:_ 
docker run -p 7777:8888 -p 6006:6006  -v /data/DeepRain/Data:/notebooks/local/ -it 
 oduerr/tf_docker:cpu_r
 -v PATH_ON_VM:LOCATION_ON_NOTEBOOK 

_Connect with ssh_
ssh -N -f -L localhost:7777:localhost:7777 clusteruser@141.37.176.202

After executing import tensorflow as tf
=> The kernel appears to have died. It will restart automatically.

**Comment by etgramli** [comment]
Die neueste Version von TF liefert folgene Fehlermeldung:
2019-06-20 12:28:54.309547: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine.

Eine aktuelle Version muss man evt selbt kompilieren: https://www.tensorflow.org/install/source
Vielleicht hilft auch:
https://stackoverflow.com/questions/41293077/how-to-compile-tensorflow-with-sse4-2-and-avx-instructions

**Comment by etgramli** [comment]
In Python erscheint beim Versneden von neuem Code mit V1.5.0:



ImportErrorTraceback (most recent call last)
<ipython-input-15-8ce07ce19120> in <module>
----> 1 from extendet_CNN_test import train_realdata
      2 train_realdata(model, sb, n_epoch=80, savename="{FEHLERFUNKTIONSNAME}", channelsLast=True, use_logfile=True,
      3 load_last_state=True)

/notebooks/local/NetworkTypes/extendet_CNN_test.py in <module>
      4 import numpy as np
      5 import os
----> 6 from tensorflow.keras.models import load_model
      7 import matplotlib.pyplot as plt
      8 import keras

ImportError: No module named 'tensorflow.keras'

**Comment by etgramli** [comment]
Docker images anzeigen:
docker images

Docker container anzeigen:
docker ps

Docker im Hintergrund starten:
docker run -dt <image-id>

Sich per Bash mit Docker-Container verbinden:
docker exec -it <container-id> /bin/bash

Änderungen am image speichern (!!! falls nicht im Hintergund gestartet von zweiter Shell !!!):
docker commit <container-id> <image-id>:<tag>
