### ISSUE TITLE
LossFunktion anpassen

### ISSUE THREAD

**Issue by thgnaedi** [thgnaedi/DeepRain#23]
https://arxiv.org/pdf/1701.05517.pdf
Auch mal als Klassifikation machen

**Comment by thgnaedi** [comment]
Vorgehen siehe Wiki: https://github.com/thgnaedi/DeepRain/wiki/Fehlerfunktionen

**Comment by etgramli** [comment]
Auswertung: Confusion-Matrix, Lernkurve
Randpixel separat behandeln?
Kompletten Datensatz lernen (Training und Validation separat)

CNN für den Konstanz-Pixel (Klassifikation)
