### ISSUE TITLE
Dokumentation

### ISSUE THREAD

**Issue by etgramli** [thgnaedi/DeepRain#28]
Kapitel
- Paper und Gesamtdokumentation

- Abstract (Merle)
- Datenbeschaffung (Etienne, Tim)
- Daten-Aufbereitung (Tim)
- Datenanalyse (Merle)
- Netzwerke (Thomas, Etienne, Tim)
-- Netzwerktyp
-- Lossfunktion
-- Sensitivitätsanalyse
- Fazit
- Ausblick

**Comment by thgnaedi** [comment]
Pro Kapitel einfach ein neues *.tex File erstellen und im "Langdokumenation.tex" File als ```\input{*.tex}``` einbinden.

Pfad: https://github.com/thgnaedi/DeepRain/tree/master/Docs

**Comment by thgnaedi** [comment]
[Documentation](https://github.com/thgnaedi/DeepRain/blob/master/Docs/Langdokumentation.pdf) and [paper](https://github.com/thgnaedi/DeepRain/blob/master/Docs/paper/report.pdf) done
