### ISSUE TITLE
What is .sb file and how do i convert radar data to .sb format?

### ISSUE THREAD

**Issue by Asishinuzuka** [thgnaedi/DeepRain#30]

**Comment by thgnaedi** [comment]
Hey Asishinuzuka,

a .sb File is a stored python object wich contains samples for the training/evaluation steps. It does also provide some helpfull functions, like removing Data without rainfall or less than a specific threshold.

To create a .sb File, you first need to convert your Radardata Binarys to images (PNGs), this can be done by using the converter DWDtoPngScript.py in [Data/](https://github.com/thgnaedi/DeepRain/tree/master/Data)
after this you can create an .sb File by using an Data_converter object, wich can be found in simple_image_script.py (same directory)

To create the Object you have to set some Parameters like:
* Path to all PNGs
* max. number of samples you want to create
* number of timesteps/images for input data
* number of timesteps/images for output data (Label)

other parameters are optional and can be used to cut and scale the images.

after creating your Object you can store it as .sb File by calling the .save_object() method

a German introduction and code can be found at this [jupyterNotebook](https://github.com/thgnaedi/DeepRain/blob/master/Data/Anwendung%20simple_image_script.ipynb)

**Comment by Asishinuzuka** [comment]
Thank you so much for such a detailed answer.
