### ISSUE TITLE
VM Speicher erweitern

### ISSUE THREAD

**Issue by thgnaedi** [thgnaedi/DeepRain#4]
Aktuell hat die VM wenig Festplattenspeicher.
Wie viel Speicher wird benötigt für Wetterdaten von einem Tag ?
daraus kann grobe prognose erstellt werden, wie viel Speicher mindestens benötigt wird. Anschließend kann Speicherplatz zur verfügung gestellt werden.

**Comment by BruegelN** [comment]
Done, 200GB unter ```/data``` gemountet
