### ISSUE TITLE
Wie Korreliert Radarbild mit RegenmengenMessung

### ISSUE THREAD

**Issue by thgnaedi** [thgnaedi/DeepRain#6]
1) Wo ist Konstanz auf den Bildern
2) welche Farbe bedeutet welche Regenemenge (Skalierung)
3) vgl. zb mit statista o.ä

**Comment by thgnaedi** [comment]
Jahr 2018 in Ordnerstruktur Packen
Prio liegt auf Juni 2018. als Grayscale

**Comment by etgramli** [comment]
Die Skalierung von ganz 2018 dauert leider lange, aber eine Multi-Threaded-Version läuft schon auf der VM.

**Comment by thgnaedi** [comment]
Blocked by Issue #11 
Bis dahin nur grober Algorithmus möglich, keine Auswertung derzeit sinnvoll.

**Comment by thgnaedi** [comment]
weiterhin auf Bilder warten,
Auswertung evtl. in R

**Comment by thgnaedi** [comment]
Auf VM werden derzeit die Bilder zu 2016 Erstellt, Issue also mit einem regenreichen Monat aus 2016 weiterführen.

**Comment by thgnaedi** [comment]
Ein Monat ziehen und mit R matchen
evtl. package deplyr // bei r-bloggers nachschauen

**Comment by WandaWuff** [comment]
Wegen Krankheit nicht so viel geschafft wie erhofft. 
Python script zum aufrechnen der regenmenge alle fünf Minuten. 
Nächster Schritt: download der pngs und Auflistung der Pixel in einer Tabelle zum späteren Vergleich
